[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "dist"                 # Vite output directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200               # Handle SPA routing