[build]
  command = "npm run build"
  publish = "build"  # Fixed: Correct quotes, removed leading slash
  base = ""          # Empty base for root-level frontend

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200       # Required for React SPA routing